#############################################################################
# Makefile for building: ai_csi_test
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  ai_csi_test.pro
# Template: app
# Command: /mnt/share/qt/qt-arm-sdk/bin/qmake -o Makefile ai_csi_test.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = aarch64-linux-gnu-gcc
CXX           = aarch64-linux-gnu-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -IcameraV4L2 -Iai -I../../ai_learn/ncnn-install/include/ncnn -I../qt-arm-sdk/include -I../qt-arm-sdk/include/QtWidgets -I../qt-arm-sdk/include/QtGui -I../qt-arm-sdk/include/QtCore -I. -I. -I../qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++
QMAKE         = /mnt/share/qt/qt-arm-sdk/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /mnt/share/qt/qt-arm-sdk/bin/qmake -install qinstall
QINSTALL_PROGRAM = /mnt/share/qt/qt-arm-sdk/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ai_csi_test1.0.0
DISTDIR = /mnt/share/qt/ai_csi_test/.tmp/ai_csi_test1.0.0
LINK          = aarch64-linux-gnu-g++
LFLAGS        = -fopenmp -Wl,-O1 -Wl,-rpath,/mnt/share/qt/qt-arm-sdk/lib
LIBS          = $(SUBLIBS) -L/home/gg/test/ai_test/ncnn/build/src -lncnn /mnt/share/qt/qt-arm-sdk/lib/libQt5Widgets.so /mnt/share/qt/qt-arm-sdk/lib/libQt5Gui.so /mnt/share/qt/qt-arm-sdk/lib/libQt5Core.so -lpthread   
AR            = aarch64-linux-gnu-ar cqs
RANLIB        = 
SED           = sed
STRIP         = aarch64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cameraV4L2/CameraV4L2.cpp \
		cameraV4L2/image_converter.cpp \
		ai/yolov5.cpp \
		main.cpp \
		mainwindow.cpp \
		CameraEngine.cpp \
		YoloEngine.cpp moc_mainwindow.cpp
OBJECTS       = CameraV4L2.o \
		image_converter.o \
		yolov5.o \
		main.o \
		mainwindow.o \
		CameraEngine.o \
		YoloEngine.o \
		moc_mainwindow.o
DIST          = ../qt-arm-sdk/mkspecs/features/spec_pre.prf \
		../qt-arm-sdk/mkspecs/common/unix.conf \
		../qt-arm-sdk/mkspecs/common/linux.conf \
		../qt-arm-sdk/mkspecs/common/sanitize.conf \
		../qt-arm-sdk/mkspecs/common/gcc-base.conf \
		../qt-arm-sdk/mkspecs/common/gcc-base-unix.conf \
		../qt-arm-sdk/mkspecs/common/g++-base.conf \
		../qt-arm-sdk/mkspecs/common/g++-unix.conf \
		../qt-arm-sdk/mkspecs/qconfig.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_charts.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_charts_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_core.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_core_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_dbus.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gui.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gui_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_help.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_help_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_location.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_location_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_network.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_network_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_nfc.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioning.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quick.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quick_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_repparser.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_script.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_script_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scxml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sensors.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialport.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sql.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sql_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_svg.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_svg_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_testlib.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uitools.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_websockets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webview.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webview_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_widgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt-arm-sdk/mkspecs/features/qt_functions.prf \
		../qt-arm-sdk/mkspecs/features/qt_config.prf \
		../qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++/qmake.conf \
		../qt-arm-sdk/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt-arm-sdk/mkspecs/features/exclusive_builds.prf \
		../qt-arm-sdk/mkspecs/features/toolchain.prf \
		../qt-arm-sdk/mkspecs/features/default_pre.prf \
		../qt-arm-sdk/mkspecs/features/resolve_config.prf \
		../qt-arm-sdk/mkspecs/features/default_post.prf \
		../qt-arm-sdk/mkspecs/features/warn_on.prf \
		../qt-arm-sdk/mkspecs/features/qt.prf \
		../qt-arm-sdk/mkspecs/features/resources.prf \
		../qt-arm-sdk/mkspecs/features/moc.prf \
		../qt-arm-sdk/mkspecs/features/uic.prf \
		../qt-arm-sdk/mkspecs/features/unix/thread.prf \
		../qt-arm-sdk/mkspecs/features/qmake_use.prf \
		../qt-arm-sdk/mkspecs/features/file_copies.prf \
		../qt-arm-sdk/mkspecs/features/testcase_targets.prf \
		../qt-arm-sdk/mkspecs/features/exceptions.prf \
		../qt-arm-sdk/mkspecs/features/yacc.prf \
		../qt-arm-sdk/mkspecs/features/lex.prf \
		ai_csi_test.pro cameraV4L2/CameraV4L2.h \
		cameraV4L2/image_converter.h \
		ai/yolov5.h \
		cameraV4L2/sunxi_camera_v2.h \
		cameraV4L2/sunxi_display2.h \
		mainwindow.h \
		CameraEngine.h \
		Frame.h \
		FrameBuffer.h \
		YoloEngine.h cameraV4L2/CameraV4L2.cpp \
		cameraV4L2/image_converter.cpp \
		ai/yolov5.cpp \
		main.cpp \
		mainwindow.cpp \
		CameraEngine.cpp \
		YoloEngine.cpp
QMAKE_TARGET  = ai_csi_test
DESTDIR       = 
TARGET        = ai_csi_test


first: all
####### Build rules

ai_csi_test: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ai_csi_test.pro ../qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++/qmake.conf ../qt-arm-sdk/mkspecs/features/spec_pre.prf \
		../qt-arm-sdk/mkspecs/common/unix.conf \
		../qt-arm-sdk/mkspecs/common/linux.conf \
		../qt-arm-sdk/mkspecs/common/sanitize.conf \
		../qt-arm-sdk/mkspecs/common/gcc-base.conf \
		../qt-arm-sdk/mkspecs/common/gcc-base-unix.conf \
		../qt-arm-sdk/mkspecs/common/g++-base.conf \
		../qt-arm-sdk/mkspecs/common/g++-unix.conf \
		../qt-arm-sdk/mkspecs/qconfig.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_charts.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_charts_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_core.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_core_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_dbus.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gui.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_gui_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_help.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_help_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_location.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_location_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_network.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_network_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_nfc.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioning.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quick.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quick_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_repparser.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_script.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_script_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scxml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sensors.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialport.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sql.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_sql_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_svg.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_svg_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_testlib.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uitools.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_websockets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webview.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_webview_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_widgets.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xml.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xml_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt-arm-sdk/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt-arm-sdk/mkspecs/features/qt_functions.prf \
		../qt-arm-sdk/mkspecs/features/qt_config.prf \
		../qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++/qmake.conf \
		../qt-arm-sdk/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt-arm-sdk/mkspecs/features/exclusive_builds.prf \
		../qt-arm-sdk/mkspecs/features/toolchain.prf \
		../qt-arm-sdk/mkspecs/features/default_pre.prf \
		../qt-arm-sdk/mkspecs/features/resolve_config.prf \
		../qt-arm-sdk/mkspecs/features/default_post.prf \
		../qt-arm-sdk/mkspecs/features/warn_on.prf \
		../qt-arm-sdk/mkspecs/features/qt.prf \
		../qt-arm-sdk/mkspecs/features/resources.prf \
		../qt-arm-sdk/mkspecs/features/moc.prf \
		../qt-arm-sdk/mkspecs/features/uic.prf \
		../qt-arm-sdk/mkspecs/features/unix/thread.prf \
		../qt-arm-sdk/mkspecs/features/qmake_use.prf \
		../qt-arm-sdk/mkspecs/features/file_copies.prf \
		../qt-arm-sdk/mkspecs/features/testcase_targets.prf \
		../qt-arm-sdk/mkspecs/features/exceptions.prf \
		../qt-arm-sdk/mkspecs/features/yacc.prf \
		../qt-arm-sdk/mkspecs/features/lex.prf \
		ai_csi_test.pro
	$(QMAKE) -o Makefile ai_csi_test.pro
../qt-arm-sdk/mkspecs/features/spec_pre.prf:
../qt-arm-sdk/mkspecs/common/unix.conf:
../qt-arm-sdk/mkspecs/common/linux.conf:
../qt-arm-sdk/mkspecs/common/sanitize.conf:
../qt-arm-sdk/mkspecs/common/gcc-base.conf:
../qt-arm-sdk/mkspecs/common/gcc-base-unix.conf:
../qt-arm-sdk/mkspecs/common/g++-base.conf:
../qt-arm-sdk/mkspecs/common/g++-unix.conf:
../qt-arm-sdk/mkspecs/qconfig.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_charts.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_charts_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_core.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_core_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_dbus.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_dbus_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_edid_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_gamepad_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_gui.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_gui_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_help.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_help_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_input_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_location.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_location_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_network.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_network_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_networkauth_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_nfc.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_nfc_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_positioning.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_positioning_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_positioningquick_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_purchasing_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qml.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qml_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quick.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quick_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quickshapes_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_repparser.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_repparser_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_script.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_script_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_scripttools_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_scxml.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_scxml_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_sensors.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_sensors_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_serialbus_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_serialport.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_serialport_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_service_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_sql.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_sql_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_svg.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_svg_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_testlib.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_testlib_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_texttospeech_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_theme_support_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_uiplugin.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_uitools.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_uitools_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_webchannel_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_websockets.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_websockets_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_webview.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_webview_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_widgets.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_widgets_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_xml.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_xml_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt-arm-sdk/mkspecs/modules/qt_lib_zlib_private.pri:
../qt-arm-sdk/mkspecs/features/qt_functions.prf:
../qt-arm-sdk/mkspecs/features/qt_config.prf:
../qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++/qmake.conf:
../qt-arm-sdk/mkspecs/features/spec_post.prf:
.qmake.stash:
../qt-arm-sdk/mkspecs/features/exclusive_builds.prf:
../qt-arm-sdk/mkspecs/features/toolchain.prf:
../qt-arm-sdk/mkspecs/features/default_pre.prf:
../qt-arm-sdk/mkspecs/features/resolve_config.prf:
../qt-arm-sdk/mkspecs/features/default_post.prf:
../qt-arm-sdk/mkspecs/features/warn_on.prf:
../qt-arm-sdk/mkspecs/features/qt.prf:
../qt-arm-sdk/mkspecs/features/resources.prf:
../qt-arm-sdk/mkspecs/features/moc.prf:
../qt-arm-sdk/mkspecs/features/uic.prf:
../qt-arm-sdk/mkspecs/features/unix/thread.prf:
../qt-arm-sdk/mkspecs/features/qmake_use.prf:
../qt-arm-sdk/mkspecs/features/file_copies.prf:
../qt-arm-sdk/mkspecs/features/testcase_targets.prf:
../qt-arm-sdk/mkspecs/features/exceptions.prf:
../qt-arm-sdk/mkspecs/features/yacc.prf:
../qt-arm-sdk/mkspecs/features/lex.prf:
ai_csi_test.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ai_csi_test.pro

qmake_all: FORCE


all: Makefile ai_csi_test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../qt-arm-sdk/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cameraV4L2/CameraV4L2.h cameraV4L2/image_converter.h ai/yolov5.h cameraV4L2/sunxi_camera_v2.h cameraV4L2/sunxi_display2.h mainwindow.h CameraEngine.h Frame.h FrameBuffer.h YoloEngine.h $(DISTDIR)/
	$(COPY_FILE) --parents cameraV4L2/CameraV4L2.cpp cameraV4L2/image_converter.cpp ai/yolov5.cpp main.cpp mainwindow.cpp CameraEngine.cpp YoloEngine.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/
	$(COPY_FILE) --parents ai_csi_test_zh_CN.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../qt-arm-sdk/mkspecs/features/data/dummy.cpp
	aarch64-linux-gnu-g++ -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../qt-arm-sdk/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../qt-arm-sdk/include/QtWidgets/QMainWindow \
		../qt-arm-sdk/include/QtWidgets/qmainwindow.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgetsglobal.h \
		../qt-arm-sdk/include/QtGui/qtguiglobal.h \
		../qt-arm-sdk/include/QtCore/qglobal.h \
		../qt-arm-sdk/include/QtCore/qconfig-bootstrapped.h \
		../qt-arm-sdk/include/QtCore/qconfig.h \
		../qt-arm-sdk/include/QtCore/qtcore-config.h \
		../qt-arm-sdk/include/QtCore/qsystemdetection.h \
		../qt-arm-sdk/include/QtCore/qprocessordetection.h \
		../qt-arm-sdk/include/QtCore/qcompilerdetection.h \
		../qt-arm-sdk/include/QtCore/qtypeinfo.h \
		../qt-arm-sdk/include/QtCore/qsysinfo.h \
		../qt-arm-sdk/include/QtCore/qlogging.h \
		../qt-arm-sdk/include/QtCore/qflags.h \
		../qt-arm-sdk/include/QtCore/qatomic.h \
		../qt-arm-sdk/include/QtCore/qbasicatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_bootstrap.h \
		../qt-arm-sdk/include/QtCore/qgenericatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_cxx11.h \
		../qt-arm-sdk/include/QtCore/qatomic_msvc.h \
		../qt-arm-sdk/include/QtCore/qglobalstatic.h \
		../qt-arm-sdk/include/QtCore/qmutex.h \
		../qt-arm-sdk/include/QtCore/qnumeric.h \
		../qt-arm-sdk/include/QtCore/qversiontagging.h \
		../qt-arm-sdk/include/QtGui/qtgui-config.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgets-config.h \
		../qt-arm-sdk/include/QtWidgets/qwidget.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs.h \
		../qt-arm-sdk/include/QtCore/qnamespace.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs_impl.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs_win.h \
		../qt-arm-sdk/include/QtCore/qobject.h \
		../qt-arm-sdk/include/QtCore/qstring.h \
		../qt-arm-sdk/include/QtCore/qchar.h \
		../qt-arm-sdk/include/QtCore/qbytearray.h \
		../qt-arm-sdk/include/QtCore/qrefcount.h \
		../qt-arm-sdk/include/QtCore/qarraydata.h \
		../qt-arm-sdk/include/QtCore/qstringliteral.h \
		../qt-arm-sdk/include/QtCore/qstringalgorithms.h \
		../qt-arm-sdk/include/QtCore/qstringview.h \
		../qt-arm-sdk/include/QtCore/qstringbuilder.h \
		../qt-arm-sdk/include/QtCore/qlist.h \
		../qt-arm-sdk/include/QtCore/qalgorithms.h \
		../qt-arm-sdk/include/QtCore/qiterator.h \
		../qt-arm-sdk/include/QtCore/qhashfunctions.h \
		../qt-arm-sdk/include/QtCore/qpair.h \
		../qt-arm-sdk/include/QtCore/qbytearraylist.h \
		../qt-arm-sdk/include/QtCore/qstringlist.h \
		../qt-arm-sdk/include/QtCore/qregexp.h \
		../qt-arm-sdk/include/QtCore/qstringmatcher.h \
		../qt-arm-sdk/include/QtCore/qcoreevent.h \
		../qt-arm-sdk/include/QtCore/qscopedpointer.h \
		../qt-arm-sdk/include/QtCore/qmetatype.h \
		../qt-arm-sdk/include/QtCore/qvarlengtharray.h \
		../qt-arm-sdk/include/QtCore/qcontainerfwd.h \
		../qt-arm-sdk/include/QtCore/qobject_impl.h \
		../qt-arm-sdk/include/QtCore/qmargins.h \
		../qt-arm-sdk/include/QtGui/qpaintdevice.h \
		../qt-arm-sdk/include/QtCore/qrect.h \
		../qt-arm-sdk/include/QtCore/qsize.h \
		../qt-arm-sdk/include/QtCore/qpoint.h \
		../qt-arm-sdk/include/QtGui/qpalette.h \
		../qt-arm-sdk/include/QtGui/qcolor.h \
		../qt-arm-sdk/include/QtGui/qrgb.h \
		../qt-arm-sdk/include/QtGui/qrgba64.h \
		../qt-arm-sdk/include/QtGui/qbrush.h \
		../qt-arm-sdk/include/QtCore/qvector.h \
		../qt-arm-sdk/include/QtGui/qmatrix.h \
		../qt-arm-sdk/include/QtGui/qpolygon.h \
		../qt-arm-sdk/include/QtGui/qregion.h \
		../qt-arm-sdk/include/QtCore/qdatastream.h \
		../qt-arm-sdk/include/QtCore/qiodevice.h \
		../qt-arm-sdk/include/QtCore/qline.h \
		../qt-arm-sdk/include/QtGui/qtransform.h \
		../qt-arm-sdk/include/QtGui/qpainterpath.h \
		../qt-arm-sdk/include/QtGui/qimage.h \
		../qt-arm-sdk/include/QtGui/qpixelformat.h \
		../qt-arm-sdk/include/QtGui/qpixmap.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer.h \
		../qt-arm-sdk/include/QtCore/qshareddata.h \
		../qt-arm-sdk/include/QtCore/qhash.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer_impl.h \
		../qt-arm-sdk/include/QtGui/qfont.h \
		../qt-arm-sdk/include/QtGui/qfontmetrics.h \
		../qt-arm-sdk/include/QtGui/qfontinfo.h \
		../qt-arm-sdk/include/QtWidgets/qsizepolicy.h \
		../qt-arm-sdk/include/QtGui/qcursor.h \
		../qt-arm-sdk/include/QtGui/qkeysequence.h \
		../qt-arm-sdk/include/QtGui/qevent.h \
		../qt-arm-sdk/include/QtCore/qvariant.h \
		../qt-arm-sdk/include/QtCore/qmap.h \
		../qt-arm-sdk/include/QtCore/qdebug.h \
		../qt-arm-sdk/include/QtCore/qtextstream.h \
		../qt-arm-sdk/include/QtCore/qlocale.h \
		../qt-arm-sdk/include/QtCore/qset.h \
		../qt-arm-sdk/include/QtCore/qcontiguouscache.h \
		../qt-arm-sdk/include/QtCore/qurl.h \
		../qt-arm-sdk/include/QtCore/qurlquery.h \
		../qt-arm-sdk/include/QtCore/qfile.h \
		../qt-arm-sdk/include/QtCore/qfiledevice.h \
		../qt-arm-sdk/include/QtGui/qvector2d.h \
		../qt-arm-sdk/include/QtGui/qtouchdevice.h \
		../qt-arm-sdk/include/QtWidgets/qtabwidget.h \
		../qt-arm-sdk/include/QtGui/qicon.h \
		../qt-arm-sdk/include/QtCore/QTimer \
		../qt-arm-sdk/include/QtCore/qtimer.h \
		../qt-arm-sdk/include/QtCore/qbasictimer.h \
		ai/yolov5.h \
		../../ai_learn/ncnn-install/include/ncnn/net.h \
		../../ai_learn/ncnn-install/include/ncnn/blob.h \
		../../ai_learn/ncnn-install/include/ncnn/mat.h \
		../../ai_learn/ncnn-install/include/ncnn/cpu.h \
		../../ai_learn/ncnn-install/include/ncnn/platform.h \
		../../ai_learn/ncnn-install/include/ncnn/ncnn_export.h \
		../../ai_learn/ncnn-install/include/ncnn/simplestl.h \
		../../ai_learn/ncnn-install/include/ncnn/simplemath.h \
		../../ai_learn/ncnn-install/include/ncnn/simplevk.h \
		../../ai_learn/ncnn-install/include/ncnn/vulkan_header_fix.h \
		../../ai_learn/ncnn-install/include/ncnn/allocator.h \
		../../ai_learn/ncnn-install/include/ncnn/option.h \
		../../ai_learn/ncnn-install/include/ncnn/layer.h \
		../../ai_learn/ncnn-install/include/ncnn/modelbin.h \
		../../ai_learn/ncnn-install/include/ncnn/paramdict.h \
		../../ai_learn/ncnn-install/include/ncnn/command.h \
		../../ai_learn/ncnn-install/include/ncnn/pipeline.h \
		../../ai_learn/ncnn-install/include/ncnn/gpu.h \
		FrameBuffer.h \
		Frame.h \
		CameraEngine.h \
		cameraV4L2/CameraV4L2.h \
		YoloEngine.h \
		moc_predefs.h \
		../qt-arm-sdk/bin/moc
	/mnt/share/qt/qt-arm-sdk/bin/moc $(DEFINES) --include /mnt/share/qt/ai_csi_test/moc_predefs.h -I/mnt/share/qt/qt-arm-sdk/mkspecs/linux-aarch64-gnu-g++ -I/mnt/share/qt/ai_csi_test -I/mnt/share/qt/ai_csi_test -I/mnt/share/qt/ai_csi_test/cameraV4L2 -I/mnt/share/qt/ai_csi_test/ai -I/mnt/share/ai_learn/ncnn-install/include/ncnn -I/mnt/share/qt/qt-arm-sdk/include -I/mnt/share/qt/qt-arm-sdk/include/QtWidgets -I/mnt/share/qt/qt-arm-sdk/include/QtGui -I/mnt/share/qt/qt-arm-sdk/include/QtCore -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/5.3.1 -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/5.3.1/aarch64-linux-gnu -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/5.3.1/backward -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/lib/gcc/aarch64-linux-gnu/5.3.1/include -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/lib/gcc/aarch64-linux-gnu/5.3.1/include-fixed -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include -I/home/gg/qt/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../qt-arm-sdk/bin/uic
	/mnt/share/qt/qt-arm-sdk/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

CameraV4L2.o: cameraV4L2/CameraV4L2.cpp cameraV4L2/CameraV4L2.h \
		Frame.h \
		cameraV4L2/image_converter.h \
		cameraV4L2/sunxi_display2.h \
		cameraV4L2/sunxi_camera_v2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CameraV4L2.o cameraV4L2/CameraV4L2.cpp

image_converter.o: cameraV4L2/image_converter.cpp cameraV4L2/image_converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image_converter.o cameraV4L2/image_converter.cpp

yolov5.o: ai/yolov5.cpp ai/yolov5.h \
		../../ai_learn/ncnn-install/include/ncnn/net.h \
		../../ai_learn/ncnn-install/include/ncnn/blob.h \
		../../ai_learn/ncnn-install/include/ncnn/mat.h \
		../../ai_learn/ncnn-install/include/ncnn/cpu.h \
		../../ai_learn/ncnn-install/include/ncnn/platform.h \
		../../ai_learn/ncnn-install/include/ncnn/ncnn_export.h \
		../../ai_learn/ncnn-install/include/ncnn/simplestl.h \
		../../ai_learn/ncnn-install/include/ncnn/simplemath.h \
		../../ai_learn/ncnn-install/include/ncnn/simplevk.h \
		../../ai_learn/ncnn-install/include/ncnn/vulkan_header_fix.h \
		../../ai_learn/ncnn-install/include/ncnn/allocator.h \
		../../ai_learn/ncnn-install/include/ncnn/option.h \
		../../ai_learn/ncnn-install/include/ncnn/layer.h \
		../../ai_learn/ncnn-install/include/ncnn/modelbin.h \
		../../ai_learn/ncnn-install/include/ncnn/paramdict.h \
		../../ai_learn/ncnn-install/include/ncnn/command.h \
		../../ai_learn/ncnn-install/include/ncnn/pipeline.h \
		../../ai_learn/ncnn-install/include/ncnn/gpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yolov5.o ai/yolov5.cpp

main.o: main.cpp mainwindow.h \
		../qt-arm-sdk/include/QtWidgets/QMainWindow \
		../qt-arm-sdk/include/QtWidgets/qmainwindow.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgetsglobal.h \
		../qt-arm-sdk/include/QtGui/qtguiglobal.h \
		../qt-arm-sdk/include/QtCore/qglobal.h \
		../qt-arm-sdk/include/QtCore/qconfig-bootstrapped.h \
		../qt-arm-sdk/include/QtCore/qconfig.h \
		../qt-arm-sdk/include/QtCore/qtcore-config.h \
		../qt-arm-sdk/include/QtCore/qsystemdetection.h \
		../qt-arm-sdk/include/QtCore/qprocessordetection.h \
		../qt-arm-sdk/include/QtCore/qcompilerdetection.h \
		../qt-arm-sdk/include/QtCore/qtypeinfo.h \
		../qt-arm-sdk/include/QtCore/qsysinfo.h \
		../qt-arm-sdk/include/QtCore/qlogging.h \
		../qt-arm-sdk/include/QtCore/qflags.h \
		../qt-arm-sdk/include/QtCore/qatomic.h \
		../qt-arm-sdk/include/QtCore/qbasicatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_bootstrap.h \
		../qt-arm-sdk/include/QtCore/qgenericatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_cxx11.h \
		../qt-arm-sdk/include/QtCore/qatomic_msvc.h \
		../qt-arm-sdk/include/QtCore/qglobalstatic.h \
		../qt-arm-sdk/include/QtCore/qmutex.h \
		../qt-arm-sdk/include/QtCore/qnumeric.h \
		../qt-arm-sdk/include/QtCore/qversiontagging.h \
		../qt-arm-sdk/include/QtGui/qtgui-config.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgets-config.h \
		../qt-arm-sdk/include/QtWidgets/qwidget.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs.h \
		../qt-arm-sdk/include/QtCore/qnamespace.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs_impl.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs_win.h \
		../qt-arm-sdk/include/QtCore/qobject.h \
		../qt-arm-sdk/include/QtCore/qstring.h \
		../qt-arm-sdk/include/QtCore/qchar.h \
		../qt-arm-sdk/include/QtCore/qbytearray.h \
		../qt-arm-sdk/include/QtCore/qrefcount.h \
		../qt-arm-sdk/include/QtCore/qarraydata.h \
		../qt-arm-sdk/include/QtCore/qstringliteral.h \
		../qt-arm-sdk/include/QtCore/qstringalgorithms.h \
		../qt-arm-sdk/include/QtCore/qstringview.h \
		../qt-arm-sdk/include/QtCore/qstringbuilder.h \
		../qt-arm-sdk/include/QtCore/qlist.h \
		../qt-arm-sdk/include/QtCore/qalgorithms.h \
		../qt-arm-sdk/include/QtCore/qiterator.h \
		../qt-arm-sdk/include/QtCore/qhashfunctions.h \
		../qt-arm-sdk/include/QtCore/qpair.h \
		../qt-arm-sdk/include/QtCore/qbytearraylist.h \
		../qt-arm-sdk/include/QtCore/qstringlist.h \
		../qt-arm-sdk/include/QtCore/qregexp.h \
		../qt-arm-sdk/include/QtCore/qstringmatcher.h \
		../qt-arm-sdk/include/QtCore/qcoreevent.h \
		../qt-arm-sdk/include/QtCore/qscopedpointer.h \
		../qt-arm-sdk/include/QtCore/qmetatype.h \
		../qt-arm-sdk/include/QtCore/qvarlengtharray.h \
		../qt-arm-sdk/include/QtCore/qcontainerfwd.h \
		../qt-arm-sdk/include/QtCore/qobject_impl.h \
		../qt-arm-sdk/include/QtCore/qmargins.h \
		../qt-arm-sdk/include/QtGui/qpaintdevice.h \
		../qt-arm-sdk/include/QtCore/qrect.h \
		../qt-arm-sdk/include/QtCore/qsize.h \
		../qt-arm-sdk/include/QtCore/qpoint.h \
		../qt-arm-sdk/include/QtGui/qpalette.h \
		../qt-arm-sdk/include/QtGui/qcolor.h \
		../qt-arm-sdk/include/QtGui/qrgb.h \
		../qt-arm-sdk/include/QtGui/qrgba64.h \
		../qt-arm-sdk/include/QtGui/qbrush.h \
		../qt-arm-sdk/include/QtCore/qvector.h \
		../qt-arm-sdk/include/QtGui/qmatrix.h \
		../qt-arm-sdk/include/QtGui/qpolygon.h \
		../qt-arm-sdk/include/QtGui/qregion.h \
		../qt-arm-sdk/include/QtCore/qdatastream.h \
		../qt-arm-sdk/include/QtCore/qiodevice.h \
		../qt-arm-sdk/include/QtCore/qline.h \
		../qt-arm-sdk/include/QtGui/qtransform.h \
		../qt-arm-sdk/include/QtGui/qpainterpath.h \
		../qt-arm-sdk/include/QtGui/qimage.h \
		../qt-arm-sdk/include/QtGui/qpixelformat.h \
		../qt-arm-sdk/include/QtGui/qpixmap.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer.h \
		../qt-arm-sdk/include/QtCore/qshareddata.h \
		../qt-arm-sdk/include/QtCore/qhash.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer_impl.h \
		../qt-arm-sdk/include/QtGui/qfont.h \
		../qt-arm-sdk/include/QtGui/qfontmetrics.h \
		../qt-arm-sdk/include/QtGui/qfontinfo.h \
		../qt-arm-sdk/include/QtWidgets/qsizepolicy.h \
		../qt-arm-sdk/include/QtGui/qcursor.h \
		../qt-arm-sdk/include/QtGui/qkeysequence.h \
		../qt-arm-sdk/include/QtGui/qevent.h \
		../qt-arm-sdk/include/QtCore/qvariant.h \
		../qt-arm-sdk/include/QtCore/qmap.h \
		../qt-arm-sdk/include/QtCore/qdebug.h \
		../qt-arm-sdk/include/QtCore/qtextstream.h \
		../qt-arm-sdk/include/QtCore/qlocale.h \
		../qt-arm-sdk/include/QtCore/qset.h \
		../qt-arm-sdk/include/QtCore/qcontiguouscache.h \
		../qt-arm-sdk/include/QtCore/qurl.h \
		../qt-arm-sdk/include/QtCore/qurlquery.h \
		../qt-arm-sdk/include/QtCore/qfile.h \
		../qt-arm-sdk/include/QtCore/qfiledevice.h \
		../qt-arm-sdk/include/QtGui/qvector2d.h \
		../qt-arm-sdk/include/QtGui/qtouchdevice.h \
		../qt-arm-sdk/include/QtWidgets/qtabwidget.h \
		../qt-arm-sdk/include/QtGui/qicon.h \
		../qt-arm-sdk/include/QtCore/QTimer \
		../qt-arm-sdk/include/QtCore/qtimer.h \
		../qt-arm-sdk/include/QtCore/qbasictimer.h \
		ai/yolov5.h \
		../../ai_learn/ncnn-install/include/ncnn/net.h \
		../../ai_learn/ncnn-install/include/ncnn/blob.h \
		../../ai_learn/ncnn-install/include/ncnn/mat.h \
		../../ai_learn/ncnn-install/include/ncnn/cpu.h \
		../../ai_learn/ncnn-install/include/ncnn/platform.h \
		../../ai_learn/ncnn-install/include/ncnn/ncnn_export.h \
		../../ai_learn/ncnn-install/include/ncnn/simplestl.h \
		../../ai_learn/ncnn-install/include/ncnn/simplemath.h \
		../../ai_learn/ncnn-install/include/ncnn/simplevk.h \
		../../ai_learn/ncnn-install/include/ncnn/vulkan_header_fix.h \
		../../ai_learn/ncnn-install/include/ncnn/allocator.h \
		../../ai_learn/ncnn-install/include/ncnn/option.h \
		../../ai_learn/ncnn-install/include/ncnn/layer.h \
		../../ai_learn/ncnn-install/include/ncnn/modelbin.h \
		../../ai_learn/ncnn-install/include/ncnn/paramdict.h \
		../../ai_learn/ncnn-install/include/ncnn/command.h \
		../../ai_learn/ncnn-install/include/ncnn/pipeline.h \
		../../ai_learn/ncnn-install/include/ncnn/gpu.h \
		FrameBuffer.h \
		Frame.h \
		CameraEngine.h \
		cameraV4L2/CameraV4L2.h \
		YoloEngine.h \
		../qt-arm-sdk/include/QtWidgets/QApplication \
		../qt-arm-sdk/include/QtWidgets/qapplication.h \
		../qt-arm-sdk/include/QtCore/qcoreapplication.h \
		../qt-arm-sdk/include/QtCore/qeventloop.h \
		../qt-arm-sdk/include/QtWidgets/qdesktopwidget.h \
		../qt-arm-sdk/include/QtGui/qguiapplication.h \
		../qt-arm-sdk/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../qt-arm-sdk/include/QtWidgets/QMainWindow \
		../qt-arm-sdk/include/QtWidgets/qmainwindow.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgetsglobal.h \
		../qt-arm-sdk/include/QtGui/qtguiglobal.h \
		../qt-arm-sdk/include/QtCore/qglobal.h \
		../qt-arm-sdk/include/QtCore/qconfig-bootstrapped.h \
		../qt-arm-sdk/include/QtCore/qconfig.h \
		../qt-arm-sdk/include/QtCore/qtcore-config.h \
		../qt-arm-sdk/include/QtCore/qsystemdetection.h \
		../qt-arm-sdk/include/QtCore/qprocessordetection.h \
		../qt-arm-sdk/include/QtCore/qcompilerdetection.h \
		../qt-arm-sdk/include/QtCore/qtypeinfo.h \
		../qt-arm-sdk/include/QtCore/qsysinfo.h \
		../qt-arm-sdk/include/QtCore/qlogging.h \
		../qt-arm-sdk/include/QtCore/qflags.h \
		../qt-arm-sdk/include/QtCore/qatomic.h \
		../qt-arm-sdk/include/QtCore/qbasicatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_bootstrap.h \
		../qt-arm-sdk/include/QtCore/qgenericatomic.h \
		../qt-arm-sdk/include/QtCore/qatomic_cxx11.h \
		../qt-arm-sdk/include/QtCore/qatomic_msvc.h \
		../qt-arm-sdk/include/QtCore/qglobalstatic.h \
		../qt-arm-sdk/include/QtCore/qmutex.h \
		../qt-arm-sdk/include/QtCore/qnumeric.h \
		../qt-arm-sdk/include/QtCore/qversiontagging.h \
		../qt-arm-sdk/include/QtGui/qtgui-config.h \
		../qt-arm-sdk/include/QtWidgets/qtwidgets-config.h \
		../qt-arm-sdk/include/QtWidgets/qwidget.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs.h \
		../qt-arm-sdk/include/QtCore/qnamespace.h \
		../qt-arm-sdk/include/QtCore/qobjectdefs_impl.h \
		../qt-arm-sdk/include/QtGui/qwindowdefs_win.h \
		../qt-arm-sdk/include/QtCore/qobject.h \
		../qt-arm-sdk/include/QtCore/qstring.h \
		../qt-arm-sdk/include/QtCore/qchar.h \
		../qt-arm-sdk/include/QtCore/qbytearray.h \
		../qt-arm-sdk/include/QtCore/qrefcount.h \
		../qt-arm-sdk/include/QtCore/qarraydata.h \
		../qt-arm-sdk/include/QtCore/qstringliteral.h \
		../qt-arm-sdk/include/QtCore/qstringalgorithms.h \
		../qt-arm-sdk/include/QtCore/qstringview.h \
		../qt-arm-sdk/include/QtCore/qstringbuilder.h \
		../qt-arm-sdk/include/QtCore/qlist.h \
		../qt-arm-sdk/include/QtCore/qalgorithms.h \
		../qt-arm-sdk/include/QtCore/qiterator.h \
		../qt-arm-sdk/include/QtCore/qhashfunctions.h \
		../qt-arm-sdk/include/QtCore/qpair.h \
		../qt-arm-sdk/include/QtCore/qbytearraylist.h \
		../qt-arm-sdk/include/QtCore/qstringlist.h \
		../qt-arm-sdk/include/QtCore/qregexp.h \
		../qt-arm-sdk/include/QtCore/qstringmatcher.h \
		../qt-arm-sdk/include/QtCore/qcoreevent.h \
		../qt-arm-sdk/include/QtCore/qscopedpointer.h \
		../qt-arm-sdk/include/QtCore/qmetatype.h \
		../qt-arm-sdk/include/QtCore/qvarlengtharray.h \
		../qt-arm-sdk/include/QtCore/qcontainerfwd.h \
		../qt-arm-sdk/include/QtCore/qobject_impl.h \
		../qt-arm-sdk/include/QtCore/qmargins.h \
		../qt-arm-sdk/include/QtGui/qpaintdevice.h \
		../qt-arm-sdk/include/QtCore/qrect.h \
		../qt-arm-sdk/include/QtCore/qsize.h \
		../qt-arm-sdk/include/QtCore/qpoint.h \
		../qt-arm-sdk/include/QtGui/qpalette.h \
		../qt-arm-sdk/include/QtGui/qcolor.h \
		../qt-arm-sdk/include/QtGui/qrgb.h \
		../qt-arm-sdk/include/QtGui/qrgba64.h \
		../qt-arm-sdk/include/QtGui/qbrush.h \
		../qt-arm-sdk/include/QtCore/qvector.h \
		../qt-arm-sdk/include/QtGui/qmatrix.h \
		../qt-arm-sdk/include/QtGui/qpolygon.h \
		../qt-arm-sdk/include/QtGui/qregion.h \
		../qt-arm-sdk/include/QtCore/qdatastream.h \
		../qt-arm-sdk/include/QtCore/qiodevice.h \
		../qt-arm-sdk/include/QtCore/qline.h \
		../qt-arm-sdk/include/QtGui/qtransform.h \
		../qt-arm-sdk/include/QtGui/qpainterpath.h \
		../qt-arm-sdk/include/QtGui/qimage.h \
		../qt-arm-sdk/include/QtGui/qpixelformat.h \
		../qt-arm-sdk/include/QtGui/qpixmap.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer.h \
		../qt-arm-sdk/include/QtCore/qshareddata.h \
		../qt-arm-sdk/include/QtCore/qhash.h \
		../qt-arm-sdk/include/QtCore/qsharedpointer_impl.h \
		../qt-arm-sdk/include/QtGui/qfont.h \
		../qt-arm-sdk/include/QtGui/qfontmetrics.h \
		../qt-arm-sdk/include/QtGui/qfontinfo.h \
		../qt-arm-sdk/include/QtWidgets/qsizepolicy.h \
		../qt-arm-sdk/include/QtGui/qcursor.h \
		../qt-arm-sdk/include/QtGui/qkeysequence.h \
		../qt-arm-sdk/include/QtGui/qevent.h \
		../qt-arm-sdk/include/QtCore/qvariant.h \
		../qt-arm-sdk/include/QtCore/qmap.h \
		../qt-arm-sdk/include/QtCore/qdebug.h \
		../qt-arm-sdk/include/QtCore/qtextstream.h \
		../qt-arm-sdk/include/QtCore/qlocale.h \
		../qt-arm-sdk/include/QtCore/qset.h \
		../qt-arm-sdk/include/QtCore/qcontiguouscache.h \
		../qt-arm-sdk/include/QtCore/qurl.h \
		../qt-arm-sdk/include/QtCore/qurlquery.h \
		../qt-arm-sdk/include/QtCore/qfile.h \
		../qt-arm-sdk/include/QtCore/qfiledevice.h \
		../qt-arm-sdk/include/QtGui/qvector2d.h \
		../qt-arm-sdk/include/QtGui/qtouchdevice.h \
		../qt-arm-sdk/include/QtWidgets/qtabwidget.h \
		../qt-arm-sdk/include/QtGui/qicon.h \
		../qt-arm-sdk/include/QtCore/QTimer \
		../qt-arm-sdk/include/QtCore/qtimer.h \
		../qt-arm-sdk/include/QtCore/qbasictimer.h \
		ai/yolov5.h \
		../../ai_learn/ncnn-install/include/ncnn/net.h \
		../../ai_learn/ncnn-install/include/ncnn/blob.h \
		../../ai_learn/ncnn-install/include/ncnn/mat.h \
		../../ai_learn/ncnn-install/include/ncnn/cpu.h \
		../../ai_learn/ncnn-install/include/ncnn/platform.h \
		../../ai_learn/ncnn-install/include/ncnn/ncnn_export.h \
		../../ai_learn/ncnn-install/include/ncnn/simplestl.h \
		../../ai_learn/ncnn-install/include/ncnn/simplemath.h \
		../../ai_learn/ncnn-install/include/ncnn/simplevk.h \
		../../ai_learn/ncnn-install/include/ncnn/vulkan_header_fix.h \
		../../ai_learn/ncnn-install/include/ncnn/allocator.h \
		../../ai_learn/ncnn-install/include/ncnn/option.h \
		../../ai_learn/ncnn-install/include/ncnn/layer.h \
		../../ai_learn/ncnn-install/include/ncnn/modelbin.h \
		../../ai_learn/ncnn-install/include/ncnn/paramdict.h \
		../../ai_learn/ncnn-install/include/ncnn/command.h \
		../../ai_learn/ncnn-install/include/ncnn/pipeline.h \
		../../ai_learn/ncnn-install/include/ncnn/gpu.h \
		FrameBuffer.h \
		Frame.h \
		CameraEngine.h \
		cameraV4L2/CameraV4L2.h \
		YoloEngine.h \
		ui_mainwindow.h \
		../qt-arm-sdk/include/QtCore/QVariant \
		../qt-arm-sdk/include/QtWidgets/QAction \
		../qt-arm-sdk/include/QtWidgets/qaction.h \
		../qt-arm-sdk/include/QtWidgets/qactiongroup.h \
		../qt-arm-sdk/include/QtWidgets/QApplication \
		../qt-arm-sdk/include/QtWidgets/qapplication.h \
		../qt-arm-sdk/include/QtCore/qcoreapplication.h \
		../qt-arm-sdk/include/QtCore/qeventloop.h \
		../qt-arm-sdk/include/QtWidgets/qdesktopwidget.h \
		../qt-arm-sdk/include/QtGui/qguiapplication.h \
		../qt-arm-sdk/include/QtGui/qinputmethod.h \
		../qt-arm-sdk/include/QtWidgets/QGroupBox \
		../qt-arm-sdk/include/QtWidgets/qgroupbox.h \
		../qt-arm-sdk/include/QtWidgets/qframe.h \
		../qt-arm-sdk/include/QtWidgets/QLabel \
		../qt-arm-sdk/include/QtWidgets/qlabel.h \
		../qt-arm-sdk/include/QtWidgets/QPushButton \
		../qt-arm-sdk/include/QtWidgets/qpushbutton.h \
		../qt-arm-sdk/include/QtWidgets/qabstractbutton.h \
		../qt-arm-sdk/include/QtWidgets/QStatusBar \
		../qt-arm-sdk/include/QtWidgets/qstatusbar.h \
		../qt-arm-sdk/include/QtWidgets/QWidget \
		../qt-arm-sdk/include/QtCore/QDebug \
		../qt-arm-sdk/include/QtCore/QElapsedTimer \
		../qt-arm-sdk/include/QtCore/qelapsedtimer.h \
		../qt-arm-sdk/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

CameraEngine.o: CameraEngine.cpp CameraEngine.h \
		cameraV4L2/CameraV4L2.h \
		Frame.h \
		FrameBuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CameraEngine.o CameraEngine.cpp

YoloEngine.o: YoloEngine.cpp YoloEngine.h \
		ai/yolov5.h \
		../../ai_learn/ncnn-install/include/ncnn/net.h \
		../../ai_learn/ncnn-install/include/ncnn/blob.h \
		../../ai_learn/ncnn-install/include/ncnn/mat.h \
		../../ai_learn/ncnn-install/include/ncnn/cpu.h \
		../../ai_learn/ncnn-install/include/ncnn/platform.h \
		../../ai_learn/ncnn-install/include/ncnn/ncnn_export.h \
		../../ai_learn/ncnn-install/include/ncnn/simplestl.h \
		../../ai_learn/ncnn-install/include/ncnn/simplemath.h \
		../../ai_learn/ncnn-install/include/ncnn/simplevk.h \
		../../ai_learn/ncnn-install/include/ncnn/vulkan_header_fix.h \
		../../ai_learn/ncnn-install/include/ncnn/allocator.h \
		../../ai_learn/ncnn-install/include/ncnn/option.h \
		../../ai_learn/ncnn-install/include/ncnn/layer.h \
		../../ai_learn/ncnn-install/include/ncnn/modelbin.h \
		../../ai_learn/ncnn-install/include/ncnn/paramdict.h \
		../../ai_learn/ncnn-install/include/ncnn/command.h \
		../../ai_learn/ncnn-install/include/ncnn/pipeline.h \
		../../ai_learn/ncnn-install/include/ncnn/gpu.h \
		Frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o YoloEngine.o YoloEngine.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ai_csi_test/bin || mkdir -p $(INSTALL_ROOT)/opt/ai_csi_test/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ai_csi_test/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ai_csi_test/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ai_csi_test/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ai_csi_test/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

